# Generated by Django 6.1.1 on 2026-09-21 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Rastogi Traders | रस्तोगी ट्रेडर्स', max_length=200, verbose_name='दुकान / व्यवसाय का नाम (Business Name)')),
                ('tagline', models.CharField(default='किसानों की खेती का भरोसेमंद साथी', max_length=255, verbose_name='मुख्य टैगलाइन (Tagline)')),
                ('hero_subtitle', models.CharField(default='उर्वरक • कीटनाशक • पशु आहार', max_length=255, verbose_name='हीरो उप-शीर्षक (Hero Subtitle)')),
                ('hero_supporting_text', models.TextField(default='खेती और पशुपालन से जुड़े आवश्यक उत्पादों के लिए हमसे संपर्क करें। स्थानीय किसानों का सच्चा साथी।', verbose_name='हीरो विवरण (Hero Supporting Text)')),
                ('owner_name', models.CharField(default='रस्तोगी परिवार', max_length=150, verbose_name='संचालक का नाम (Owner / Family Name)')),
                ('phone_primary', models.CharField(default='+91 9876543210', max_length=20, verbose_name='प्राथमिक फोन नंबर (Primary Call Number)')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='अतिरिक्त फोन नंबर (Secondary Phone - Optional)')),
                ('whatsapp_number', models.CharField(default='+919876543210', max_length=20, verbose_name='व्हाट्सऐप नंबर (WhatsApp Number with Country Code)')),
                ('email', models.EmailField(blank=True, default='info@rastogitraders.in', max_length=254, verbose_name='ईमेल (Email Address - Optional)')),
                ('address', models.TextField(default='मुख्य बाजार, कृषि सेवा केंद्र के पास, (तहसील / जिला क्षेत्र)', verbose_name='दुकान का पूरा पता (Shop Address)')),
                ('landmark', models.CharField(blank=True, default='कृषि मंडी रोड के निकट', max_length=200, verbose_name='लैंडमार्क / पहचान (Landmark)')),
                ('city_district', models.CharField(default='सीतापुर / लखीमपुर क्षेत्र', max_length=100, verbose_name='शहर / जिला (City / District)')),
                ('state_pincode', models.CharField(default='उत्तर प्रदेश', max_length=100, verbose_name='राज्य / पिन कोड (State / PIN)')),
                ('opening_hours', models.CharField(default='सुबह 8:00 बजे से शाम 8:00 बजे तक (सोमवार - शनिवार)', max_length=200, verbose_name='खुलने का समय (Opening Hours)')),
                ('sunday_hours', models.CharField(blank=True, default='रविवार: सुबह 9:00 से दोपहर 2:00 बजे तक', max_length=100, verbose_name='रविवार का समय (Sunday Hours)')),
                ('google_maps_directions_url', models.URLField(blank=True, default='https://maps.google.com/?q=Rastogi+Traders', max_length=500, verbose_name='गूगल मैप्स दिशा-निर्देश लिंक (Google Maps Directions Link)')),
                ('google_maps_embed_url', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d113944.37684877717!2d80.61286884351336!3d27.568478470559196!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3998e3b7b396e9cf%3A0x6b4aa9bece4c5417!2sSitapur%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin', verbose_name='गूगल मैप्स एम्बेड URL (Google Maps Embed Iframe Src)')),
                ('about_story', models.TextField(default='Rastogi Traders एक स्थानीय कृषि उत्पाद व्यवसाय है, जहाँ किसानों और पशुपालकों के लिए उर्वरक, फसल सुरक्षा उत्पाद और पशु आहार उपलब्ध कराए जाते हैं। हमारा उद्देश्य ग्राहकों को आवश्यक कृषि उत्पादों की जानकारी और आसान संपर्क सुविधा प्रदान करना है। कई वर्षों के भरोसे और उत्तम सेवा के साथ हम हर किसान की खुशहाली के प्रति समर्पित हैं।', verbose_name='हमारे बारे में पूरी कहानी (About Business Story)')),
                ('about_short_text', models.TextField(default='उच्च गुणवत्ता वाले कृषि उत्पाद, उचित परामर्श और स्थानीय किसानों का अटूट विश्वास।', verbose_name='संक्षिप्त परिचय (About Short Description)')),
                ('trust_point_1_title', models.CharField(default='स्थानीय एवं भरोसेमंद सेवा', max_length=100, verbose_name='भरोसा बिंदु 1 शीर्षक')),
                ('trust_point_1_desc', models.CharField(default='स्थानीय किसानों और ग्राहकों के लिए आसान और विश्वसनीय संपर्क।', max_length=255, verbose_name='भरोसा बिंदु 1 विवरण')),
                ('trust_point_2_title', models.CharField(default='विभिन्न कृषि उत्पाद', max_length=100, verbose_name='भरोसा बिंदु 2 शीर्षक')),
                ('trust_point_2_desc', models.CharField(default='उर्वरक, फसल सुरक्षा उत्पाद (कीटनाशक) और पौष्टिक पशु आहार एक ही छत के नीचे।', max_length=255, verbose_name='भरोसा बिंदु 2 विवरण')),
                ('trust_point_3_title', models.CharField(default='आसान संपर्क सुविधा', max_length=100, verbose_name='भरोसा बिंदु 3 शीर्षक')),
                ('trust_point_3_desc', models.CharField(default='फोन और WhatsApp के माध्यम से आज का भाव और उत्पाद उपलब्धता तुरंत जानें।', max_length=255, verbose_name='भरोसा बिंदु 3 विवरण')),
                ('trust_point_4_title', models.CharField(default='दुकान पर सीधी उपलब्धता', max_length=100, verbose_name='भरोसा बिंदु 4 शीर्षक')),
                ('trust_point_4_desc', models.CharField(default='असली और ब्रांडेड कंपनियों के स्टॉक की दुकान पर सीधी जाँच और खरीद।', max_length=255, verbose_name='भरोसा बिंदु 4 विवरण')),
                ('facebook_url', models.URLField(blank=True, verbose_name='फेसबुक लिंक (Facebook URL)')),
                ('instagram_url', models.URLField(blank=True, verbose_name='इंस्टाग्राम लिंक (Instagram URL)')),
                ('youtube_url', models.URLField(blank=True, verbose_name='यूट्यूब लिंक (YouTube URL)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='दुकान का लोगो (Logo)')),
                ('hero_banner', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='हीरो बैनर फोटो (Hero Banner Image)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'दुकान की जानकारी (Business Profile)',
                'verbose_name_plural': 'दुकान की जानकारी (Business Profile)',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='नाम (Name)')),
                ('phone', models.CharField(max_length=20, verbose_name='मोबाइल नंबर (Mobile Phone)')),
                ('village', models.CharField(blank=True, max_length=150, verbose_name='गाँव / स्थान (Village / Location)')),
                ('interested_category', models.CharField(blank=True, max_length=100, verbose_name='रुचि का विषय / उत्पाद (Interested In)')),
                ('message', models.TextField(verbose_name='संदेश / पूछताछ (Message)')),
                ('is_read', models.BooleanField(default=False, verbose_name='पढ़ा गया (Is Read)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='प्राप्ति समय (Received At)')),
            ],
            options={
                'verbose_name': 'पूछताछ संदेश (Contact Enquiry)',
                'verbose_name_plural': 'वेबसाइट पूछताछ संदेश (Customer Enquiries)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='फोटो का शीर्षक (Title)')),
                ('category', models.CharField(choices=[('shop', 'दुकान व काउंटर (Shop & Counter)'), ('stock', 'उर्वरक एवं बीज स्टॉक (Fertilizers & Seeds Stock)'), ('cattle_feed', 'पशु आहार स्टॉक (Cattle Feed Stock)'), ('farmers', 'किसान व कृषि परिवेश (Farmers & Fields)')], default='shop', max_length=30, verbose_name='गैलरी श्रेणी (Category)')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='तस्वीर (Image File)')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='कैप्शन (Caption - Optional)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='मुख्य पृष्ठ पर दिखाएँ (Show on Homepage)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='क्रम (Display Order)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'गैलरी फोटो (Gallery Photo)',
                'verbose_name_plural': 'दुकान व स्टॉक फोटो गैलरी (Gallery Images)',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ऑफर का नाम (Offer Title)')),
                ('badge_text', models.CharField(default='सीमित समय ऑफर', max_length=80, verbose_name='बैज टेक्स्ट (Badge Text)')),
                ('description', models.TextField(verbose_name='ऑफर का विवरण (Description)')),
                ('deal_highlight', models.CharField(blank=True, max_length=150, verbose_name='मुख्य लाभ / बचत (Deal Highlight e.g. आज का विशेष भाव)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='ऑफर फोटो (Offer Image)')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='शुरुआत तिथि (Valid From)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='अंतिम तिथि (Valid Until - Optional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय है? (Is Active)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='क्रम संख्या (Display Order)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ऑफर (Offer)',
                'verbose_name_plural': 'आज के खास ऑफर (Special Offers)',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='किसान / ग्राहक का नाम (Customer Name)')),
                ('village_location', models.CharField(max_length=150, verbose_name='गाँव / कस्बा (Village / Town)')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '5 स्टार'), (4, '4 स्टार'), (3, '3 स्टार'), (2, '2 स्टार'), (1, '1 स्टार')], default=5, verbose_name='रेटिंग (Rating)')),
                ('review_text', models.TextField(verbose_name='ग्राहक की राय / अनुभव (Review Text)')),
                ('customer_photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='फोटो (Photo - Optional)')),
                ('is_approved', models.BooleanField(default=True, verbose_name='स्वीकृत / प्रदर्शित करें (Is Approved)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='क्रम (Display Order)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='दिनांक (Created At)')),
            ],
            options={
                'verbose_name': 'ग्राहक समीक्षा (Customer Review)',
                'verbose_name_plural': 'ग्राहकों की राय (Customer Reviews)',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
