# Generated by Django 6.1.1 on 2026-09-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='owner_1_desc',
            field=models.CharField(default='कृषि व्यापार एवं बीज-खाद परामर्श में 25+ वर्षों का अटूट अनुभव।', max_length=255, verbose_name='संक्षिप्त परिचय (Owner 1 Bio / Description)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner_1_name',
            field=models.CharField(default='श्री रमेश रस्तोगी', max_length=120, verbose_name='स्वामी / मुख्य संचालक का नाम (Owner 1 Name)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner_1_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/team/', verbose_name='स्वामी की फोटो (Owner 1 Photo)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner_1_role',
            field=models.CharField(default='संस्थापक एवं मुख्य संचालक (Founder & Proprietor)', max_length=100, verbose_name='पद / दायित्व (Owner 1 Role)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner_2_desc',
            field=models.CharField(default='उत्पाद उपलब्धता, स्टॉक प्रबंधन एवं किसान बंधुओं को त्वरित सेवा।', max_length=255, verbose_name='संक्षिप्त परिचय (Owner 2 Bio / Description)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner_2_name',
            field=models.CharField(default='श्री अमित रस्तोगी', max_length=120, verbose_name='प्रबंधक / सह-संचालक का नाम (Owner 2 / Manager Name)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner_2_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/team/', verbose_name='प्रबंधक की फोटो (Owner 2 / Manager Photo)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner_2_role',
            field=models.CharField(default='प्रबंधक एवं ग्राहक सेवा प्रमुख (Store Manager)', max_length=100, verbose_name='पद / दायित्व (Owner 2 / Manager Role)'),
        ),
    ]
