# Generated by Django 6.1.1 on 2026-09-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessprofile_owner_1_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='developer_credit_enabled',
            field=models.BooleanField(default=True, verbose_name='फुटर में क्रेडिट दिखाएँ? (Show Developer Credit in Footer)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='developer_credit_name',
            field=models.CharField(default='Dev Rastogi', max_length=150, verbose_name='डेवलपर का नाम / ब्रांड (Developer Name / Brand)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='developer_credit_role',
            field=models.CharField(default='वेबसाइट डिज़ाइन एवं तकनीकी विकास (Website Design & Development)', max_length=150, verbose_name='भूमिका / पद (Role / Title)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='developer_credit_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='डेवलपर लिंक / पोर्टफोलियो URL (Developer Link / Portfolio URL - Optional)'),
        ),
    ]
