# Generated by Django 6.1.1 on 2026-09-21 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name_hi', models.CharField(max_length=150, verbose_name='फसल का नाम - हिंदी (Crop Hindi Name)')),
                ('crop_name_en', models.CharField(blank=True, max_length=100, verbose_name='Crop English Name')),
                ('slug', models.SlugField(blank=True, help_text='URL identifier e.g. gehun-wheat, dhaan-paddy', max_length=150, unique=True)),
                ('icon', models.CharField(default='🌾', max_length=30, verbose_name='इमोजी आइकन (Emoji Icon e.g. 🌾, 🌱, 🌽, 🥔)')),
                ('season', models.CharField(default='रबी सीजन (Rabi Season)', max_length=100, verbose_name='मौसम / सीजन (Crop Season)')),
                ('sowing_time', models.CharField(default='अक्टूबर से दिसंबर', max_length=120, verbose_name='बुवाई का उपयुक्त समय (Sowing Time Window)')),
                ('summary', models.TextField(verbose_name='संक्षिप्त परिचय (Summary in Simple Hindi)')),
                ('soil_preparation', models.TextField(blank=True, verbose_name='खेत की तैयारी (Soil Preparation Guidelines)')),
                ('fertilizer_schedule', models.TextField(blank=True, verbose_name='उर्वरक एवं पोषण सलाह (Fertilizer Management Tips)')),
                ('irrigation_info', models.TextField(blank=True, verbose_name='सिंचाई प्रबंधन (Irrigation Schedule Stages)')),
                ('pest_management_tips', models.TextField(blank=True, verbose_name='कीट व रोग नियंत्रण सामान्य सुझाव (Pest & Disease Overview)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/', verbose_name='फसल फोटो (Crop Image)')),
                ('is_featured', models.BooleanField(default=True, verbose_name='मुख्य पृष्ठ पर दिखाएँ (Show on Home)')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय है? (Is Active)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='क्रम (Display Order)')),
            ],
            options={
                'verbose_name': 'फसल जानकारी मार्गदर्शिका (Crop Guide)',
                'verbose_name_plural': 'फसल जानकारी मार्गदर्शिकाएँ (Crop Guides)',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FarmerTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='लेख शीर्षक (Article / Tip Title)')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('category', models.CharField(choices=[('soil_fertilizer', 'उर्वरक एवं पोषण प्रबंधन (Fertilizer & Soil Care)'), ('crop_protection', 'फसल सुरक्षा एवं कीट नियंत्रण (Pest Control & Plant Protection)'), ('cattle_care', 'पशु आहार एवं डेयरी देखभाल (Cattle Feed & Livestock Care)'), ('seasonal_tips', 'मौसम अनुसार खेती के सुझाव (Seasonal Farming Tips)')], default='seasonal_tips', max_length=40, verbose_name='सलाह श्रेणी (Category)')),
                ('summary', models.TextField(verbose_name='संक्षिप्त सारांश (Summary)')),
                ('content', models.TextField(verbose_name='पूरी जानकारी एवं व्यावहारिक सुझाव (Full Article Content)')),
                ('safety_note', models.TextField(default='उत्पाद के पैकेट/लेबल पर दिए निर्देशों का पालन करें और आवश्यकता होने पर नजदीकी कृषि विशेषज्ञ से संपर्क करें।', verbose_name='सुरक्षा व वैधानिक सूचना (Safety Note / Disclaimer)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='tips/', verbose_name='मुख्य फोटो (Article Photo)')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='प्रकाशन तिथि (Published Date)')),
                ('is_published', models.BooleanField(default=True, verbose_name='प्रकाशित है? (Is Published)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='मुख्य पृष्ठ पर दिखाएँ (Featured on Homepage)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='क्रम संख्या (Display Order)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'कृषि सलाह लेख (Farmer Tip)',
                'verbose_name_plural': 'किसान सलाह व उपयोगी लेख (Farmer Tips & Articles)',
                'ordering': ['display_order', '-published_date'],
            },
        ),
    ]
