# Generated by Django 6.1.1 on 2026-09-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropguide',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL identifier (खाली छोड़ने पर स्वतः बनेगा)', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='farmertip',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL identifier (खाली छोड़ने पर स्वतः बनेगा)', max_length=250, unique=True),
        ),
    ]
