# Generated by Django 6.1.1 on 2026-09-21 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hi', models.CharField(max_length=150, verbose_name='श्रेणी का नाम - हिंदी (Category Hindi Name)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='Category English Name')),
                ('slug', models.SlugField(blank=True, help_text='URL Identifier e.g. fertilizers, pesticides, cattle-feed', max_length=150, unique=True)),
                ('icon', models.CharField(default='🌾', max_length=30, verbose_name='आइकन इमोजी / संकेत (Emoji Icon e.g. 🌾, 🌱, 🐄, 🌻)')),
                ('short_description', models.TextField(verbose_name='संक्षिप्त विवरण (Short Description in Hindi)')),
                ('badge_text', models.CharField(blank=True, default='सर्वोत्तम गुणवत्ता', max_length=50, verbose_name='बैज टैग (Badge Text)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='श्रेणी फोटो (Category Image)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='क्रम संख्या (Display Order)')),
                ('is_active', models.BooleanField(default=True, verbose_name='सक्रिय है? (Is Active)')),
            ],
            options={
                'verbose_name': 'उत्पाद श्रेणी (Product Category)',
                'verbose_name_plural': 'उत्पाद श्रेणियाँ (Product Categories)',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='उत्पाद का नाम (Product Name)')),
                ('slug', models.SlugField(blank=True, help_text='URL identifier e.g. iffco-dap-fertilizer', max_length=220, unique=True)),
                ('brand', models.CharField(default='विश्वसनीय ब्रांड', max_length=150, verbose_name='कंपनी / ब्रांड (Brand / Manufacturer)')),
                ('pack_size', models.CharField(default='50 kg / 1 Ltr / 500 gm', max_length=100, verbose_name='पैकिंग साइज (Pack Size / Unit)')),
                ('short_description', models.TextField(verbose_name='संक्षिप्त परिचय (Short Description in Hindi)')),
                ('detailed_description', models.TextField(blank=True, verbose_name='विस्तृत विवरण एवं उपयोग (Detailed Information)')),
                ('suitable_crops', models.CharField(blank=True, default='गेहूँ, धान, गन्ना, मक्का, आलू, सरसों एवं अन्य फसलें', max_length=255, verbose_name='उपयुक्त फसलें (Suitable Crops)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='उत्पाद फोटो (Product Image)')),
                ('availability_status', models.CharField(choices=[('in_stock', 'दुकान पर उपलब्ध (In Stock)'), ('limited_stock', 'सीमित स्टॉक (Limited Stock)'), ('on_order', 'ऑर्डर पर उपलब्ध (Available on Order)'), ('out_of_stock', 'वर्तमान में अनुपलब्ध (Out of Stock)')], default='in_stock', max_length=30, verbose_name='उपलब्धता स्थिति (Availability Status)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='मुख्य पृष्ठ पर दिखाएँ (Featured on Homepage)')),
                ('price_label', models.CharField(default='आज का भाव पूछें', max_length=80, verbose_name='भाव लेबल (Price Tag Label)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='वैकल्पिक निश्चित मूल्य ₹ (Optional Fixed Price)')),
                ('safety_precaution', models.TextField(default='उत्पाद के पैकेट/लेबल पर दिए निर्देशों का पालन करें और आवश्यकता होने पर कृषि विशेषज्ञ से सलाह लें।', verbose_name='सुरक्षा निर्देश एवं वैधानिक चेतावनी (Safety Precautions)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='क्रम संख्या (Display Order)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='श्रेणी (Category)')),
            ],
            options={
                'verbose_name': 'उत्पाद (Product)',
                'verbose_name_plural': 'सभी उत्पाद (All Products)',
                'ordering': ['display_order', '-id'],
            },
        ),
    ]
