# Generated by Django 6.1.1 on 2026-09-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='🌾', max_length=30, verbose_name='आइकन इमोजी / संकेत (Emoji Icon e.g. 🌾, 🌱, 🐄, 🌻)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='संक्षिप्त विवरण (Short Description in Hindi)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL Identifier e.g. fertilizers, pesticides, cattle-feed (खाली छोड़ने पर स्वतः बनेगा)', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='विश्वसनीय ब्रांड', max_length=150, verbose_name='कंपनी / ब्रांड (Brand / Manufacturer)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_size',
            field=models.CharField(blank=True, default='50 kg / 1 Ltr / 500 gm', max_length=100, verbose_name='पैकिंग साइज (Pack Size / Unit)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_label',
            field=models.CharField(blank=True, default='आज का भाव पूछें', max_length=80, verbose_name='भाव लेबल (Price Tag Label)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_precaution',
            field=models.TextField(blank=True, default='उत्पाद के पैकेट/लेबल पर दिए निर्देशों का पालन करें और आवश्यकता होने पर कृषि विशेषज्ञ से सलाह लें।', verbose_name='सुरक्षा निर्देश एवं वैधानिक चेतावनी (Safety Precautions)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='संक्षिप्त परिचय (Short Description in Hindi)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL identifier (खाली छोड़ने पर स्वतः बनेगा)', max_length=220, unique=True),
        ),
    ]
